name: Azure Zip Deploy
description: Deploy zipfile to zip deploy service
inputs:
  zip-file:
    description: the zip file
    required: true
  publish-profile:
    description: 'Publish profile (*.publishsettings) file contents with Web Deploy secrets'
    required: true
runs:
  using: node12
  main: 'dist/index.js'
branding:
  icon: archive
  color: purple